[project]
name = "mcp-leantime"
version = "0.1.0"
description = "MCP server to interact with leantime"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.12",
    "fastmcp==2.2.8",
    "httpx==0.28.1",
    "requests>=2.32.3",
]
